introduction/urls.py
from django.urls import path
from . import views

app_name='introduction'
urlpatterns = [
    path('', views.profile, name="profile"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main, name="main"),
    path('products/', include('products.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *

app_name="products"
urlpatterns = [
    path('new/', new, name='new'),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('<int:id>/', show, name="show"),
    path('<int:id>/edit/', update, name="update"),
    path('<int:product_id>/delete/', delete, name="delete"),
    path('<int:product_id>/create_comment', create_comment, name="create_comment"),
    path('<int:comment_id>/delete_comment', delete_comment, name="delete_comment"),
    path('<int:product_id>/product_like', product_like, name="product_like"),
    path('like_list', like_list, name="like_list"),
]

introduction/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    view_count = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/', null=True)
    price = models.IntegerField(null=True)
    stock = models.IntegerField(null=True)

    like_user_set = models.ManyToManyField(User, blank=True, related_name='like_user_set', through='Like')

    @property
    def like_count(self):
        return self.like_user_set.count()

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user','product'))

introduction/views.py
from django.shortcuts import render

def profile (request) :
    return render (request, 'introduction/profile.html')

myblog/views.py
from django.shortcuts import render

def main(request) :
    return render(request, 'main.html')

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Comment
from django.contrib.auth.decorators import login_required

def new(request):
    return render(request, 'products/new.html')

def create(request):
    if request.method == "POST":
        product_title = request.POST.get('title')
        product_content = request.POST.get('content')
        image = request.FILES.get('image')
        user = request.user
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        Product.objects.create(title=product_title, content=product_content, image=image, stock=stock, user=user, price=price)
    return redirect('products:main')

def main(request):
    all_products = Product.objects.all()
    return render (request, 'products/main.html', {'products': all_products})

def show(request, id):
    product = Product.objects.get(pk=id)
    increased_view_count = product.view_count + 1
    product.view_count = increased_view_count
    product.save()
    all_comments = product.comments.all().order_by('-created_at')
    return render (request, 'products/show.html', {'product': product, 'comments': all_comments})

def update(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        product.title = request.POST['title']
        product.content = request.POST['content']
        product.image = request.FILES.get('image')
        product.save()
        return redirect('products:show', product.id)
    return render(request, 'products/edit.html', {"product": product})

def delete (request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    return redirect('products:main')

def create_comment(request, product_id):
    if request.method == "POST":
        product = get_object_or_404(Product, pk=product_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment.objects.create(content=comment_content, user=current_user, product=product)
    return redirect('products:show', product_id)

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('Product', pk=product_id)

@login_required
def product_like(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product_like, product_like_created = product.like_set.get_or_create(user=request.user)

    if not product_like_created:
                product_like.delete()

    # if request.user in product.like_user_set.all():
    #     product.like_user_set.remove(request.user)
    # else:
    #     product.like_user_set.add(request.user)

    if request.GET.get('redirect_to') =='show':
            return redirect('products:show', product_id)
    else:
            return redirect('products:main')

@login_required
def like_list(request):
    likes = request.user.like_set.all()
    return render(request,'products/like_list.html',{'likes':likes})

introduction/templates/introduction/profile.html
<h1>재밌네...</h1>

myblog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>

    <title>BANGABANGA</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'shared/_navbar.html' %}
<h1>내 친구의 물건을 팔아요</h1>
<h3><진정한 아나바다의 실현!></h3>
<h3><친구들아 많이 많이 팔아죠!></h3>
<img src="{% static 'images/committhefrog.png' %}" alt="개굴개굴...왜깨지지...?">
{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">Main page</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'products:new' %}">상품판매<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:main' %}">둘러보기</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:like_list' %}">Like_list</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'account_change_password' %}">비밀번호 변경</a></li>
        {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">로그인</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">회원가입</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

products/templates/products/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1> 
    <form action="{% url 'products:update' %}" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div class="form-group">
            <label for="title">글 제목</label>
            <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해주세요." value="{{ product.title }}" required> <!-- value 속성 추가 -->
        </div>
        <div class="form-group">
            <label for="content">글 내용</label>
            <textarea class="form-control" name="content" id="content" placeholder="내용을 입력해 주세요...">{{ product.content }}</textarea> <!-- 글 내용 추가 -->
        </div>
        <div class="form-group">
            <label for="content">가격</label>
            <textarea class="form-control" name="content" id="content" placeholder="내용을 입력해 주세요...">{{ product.price }}</textarea> <!-- 글 내용 추가 -->
        </div>
        <div class="form-group">
            <label for="content">재고</label>
            <textarea class="form-control" name="content" id="content" placeholder="내용을 입력해 주세요...">{{ product.stock }}</textarea> <!-- 글 내용 추가 -->
        </div>
        <div class="form-group">
            <label>이미지 첨부</label>
            <input type="file", class="form-control" name="image" accept="image/*">
        </div>
        <input type="submit" value="글 수정" class="btn btn-outline-primary"> <!-- 수정으로 버튼 변경 -->
    </form>
</div>
{% endblock %}

products/templates/products/like_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
    <div class="container">
        {% if user.is_authenticated %}
            <h1>좋아요 한 글 목록</h1>
            <div class="row">
                {% for like in likes %}
                    <div class="col-md-4 col-12">
                        <div class="card" style="width: 18rem; margin-top: 20px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ like.product.title }}</h5>
                                <p class="card-content">{{ like.product.content }}</p>
                                <p>가격 : {{ like.product.price }}</p>
                                <p>재고 : {{ like.product.stock }}</p>
                                <p>조회수 : {{ like.product.view_count }}</p>
                                <p>좋아요 수: {{ like.product.like_count }}</p>
                                <a href="{% url 'products:product_like' like.product.id %}">
                                    {% if user in like.product.like_user_set.all %}
                                                <i class="fas fa-heart"></i>
                                    {% else %}
                                                <i class="far fa-heart"></i>
                                    {% endif %}
                                </a>
                                <a href="{% url 'products:show' like.product.pk %}" class="btn btn-primary">상세보기</a>
                            </div>
                        </div>
                    </div>
                 {% endfor %}
            </div>
        {% else %}
            <h3>로그인 후 이용이 가능합니다.</h3>
            <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
            <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
        {% endif %}
    </div>
{% endblock %}

products/templates/products/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
    <div class="container">
        {% if user.is_authenticated %}
            <h1>판매 목록</h1>
            <div class="row">
                {% for product in products %}
                    <div class="col-md-4 col-12">
                        <div class="card" style="width: 18rem; margin-top: 20px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.title }}</h5>
                                <p class="card-content">{{ product.content }}</p>
                                <p>가격 : {{ product.price }}</p>
                                <p>재고 : {{ product.stock }}</p>
                                <p>조회수 : {{ product.view_count }}</p>
                                <a href="{% url 'products:show' product.pk %}" class="btn btn-primary">상세보기</a>
                            </div>
                        </div>
                    </div>
                 {% endfor %}
            </div>
        {% else %}
            <h3>로그인 후 이용이 가능합니다.</h3>
            <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
            <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
        {% endif %}
    </div>
{% endblock %}

products/templates/products/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
    <h1>상품등록</h1>
    <form action="{% url 'products:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">글 제목</label>
            <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해주세요." required>
        </div>
        <div class="form-group">
            <label for="content">글 내용</label>
            <textarea class="form-control" name="content" id="content" placeholder="내용을 입력해 주세요..."></textarea>
        </div>
        <div class="form-group">
            <label for="price">가격</label>
            <textarea class="form-control" name="price" id="price" placeholder="내용을 입력해 주세요..."></textarea>
        </div>
        <div class="form-group">
            <label for="stock">재고</label>
            <textarea class="form-control" name="stock" id="stock" placeholder="내용을 입력해 주세요..."></textarea>
        </div>
        <div class="form-group">
            <label>이미지 첨부</label>
            <input type="file" class="form-control" name="image" accept="image/*">
        </div>
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

products/templates/products/show.html
{% extends 'base.html' %}
{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
    <h1>상품 상세 페이지</h1>
    <h3>글 제목 : {{ product.title }}</h3>
    {% if product.user %}
        {% if product.user.username == 'user' %}
            <h3>작성자: {{ product.user.last_name }} {{ product.user.first_name }} </h3>
        {% else %}
            <h3>작성자 : {{ product.user }}</h3>
        {% endif %}
    {% else %}
        <h3>작성자 : 알 수 없음</h3>
    {% endif %}
    <h3>가격 : {{ product.price }}</h3>
    <h3>재고 : {{ product.stock }}</h3>
    <h3>글 내용 : {{ product.content }}</h3>

    {% if product.image %}
        <img src="{{ product.image.url }}" alt="사진">
    {% endif %}

    <h3>조회수 : {{ product.view_count }}</h3>
    <h3>작성 시간 : {{ product.created_at }}</h3>
    <h3>수정 시간 : {{ product.updated_at }}</h3>
    <h3>좋아요 수: {{ product.like_count }}</h3>

    {% if user == product.user %}
    <a href="{% url 'products:update' product.pk %}" class="btn btn-primary">수정하기</a>
    <a href="{% url 'products:delete' product.pk %}" class="btn btn-primary">삭제하기</a>
    {% endif %}
</div>
<div class="container mt-5">
    <a href="{% url 'products:product_like' product.id %}?redirect_to=show">
        {% if user in product.like_user_set.all %}
                    <i class="fas fa-heart"></i>
        {% else %}
                    <i class="far fa-heart"></i>
        {% endif %}
    </a>
</div>
<div class="container mt-5">
    <form class="form-row" action="{% url 'products:create_comment' product.id %}" method="POST">
      {% csrf_token %}
      <textarea class="form-control col-11 mr-2" name="content" placeholder="댓글 내용 입력..."></textarea>
      <input type="submit" class="btn btn-primary" value="확인">
    </form>
</div>

<div class="container mt-5 mb-5">
    {% for comment in comments %}
        <div class="card">
            <div class="card-body">
                <b>{{ comment.user }}</b> : {{ comment.content }}<br>
                <small>{{ comment.created_at }}</small>
                    <input type="submit" class="btn btn-primary" value="수정">
                    <input type="submit" class="btn btn-primary" value="삭제">
           
                </div>
        </div>
    {% endfor %}
</div>
{% endblock %}